version: "3.9"

services:
  app:
    build:
      context: .
      args:
        PIPENV_INSTALL_ARG: "--dev"
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./:/app
    environment:
      RELOAD: "true"
      PROVISION_1: "admin:$$2b$$12$$uGQ4Y/CqHkCUqASGAJ.lmOGVNpxIj4iV6CjEZZrcbSC7iT7guo/ay"
